### ISSUE TITLE
Port set-window-hscroll

### ISSUE THREAD

**Issue by brotzeit** [remacs/remacs#1408]
```c
DEFUN ("set-window-hscroll", Fset_window_hscroll, Sset_window_hscroll, 2, 2, 0,
       doc: /* Set number of columns WINDOW is scrolled from left margin to NCOL.
WINDOW must be a live window and defaults to the selected one.
Clip the number to a reasonable value if out of range.
Return the new number.  NCOL should be zero or positive.

Note that if `automatic-hscrolling' is non-nil, you cannot scroll the
window so that the location of point moves off-window.  */)
  (Lisp_Object window, Lisp_Object ncol)
{
  CHECK_NUMBER (ncol);
  return set_window_hscroll (decode_live_window (window), XINT (ncol));
}
```

**Comment by emlun** [comment]
Hi! I'm new to the project, but I've started poking at this. I think I have it working, just need to look over if I can add some tests too.

**Comment by emlun** [comment]
Oh right, I had a couple of questions too:

 1. It looks like `ptrdiff_t` in C corresponds to `isize` in Rust, is that correct?
     1. Does that in turn mean that `min(a, PTRDIFF_MAX)` corresponds to `a as isize`?

 2. How would you suggest convertint `isize` to `EmacsInt`?

    I saw at least one `(a: isize) as EmacsInt` in the code, but `as` conversions are discouraged in the contributor guide. Since we're using nightly, is `EmacsInt::try_from(isize).expect(...)` appropriate, or is that overkill?

**Comment by shaleh** [comment]
Great questions!

Yes, isize is ptrdiff_t.
Is it min or max you are asking about?
Does `EmacsInt::from(isize_var)` work as expected?

**Comment by emlun** [comment]
I'm talking about [this C snippet][snip]:

```c
  /* Horizontal scrolling has problems with large scroll amounts.
     It's too slow with long lines, and even with small lines the
     display can be messed up.  For now, though, impose only the limits
     required by the internal representation: horizontal scrolling must
     fit in fixnum (since it's visible to Elisp) and into ptrdiff_t
     (since it's stored in a ptrdiff_t).  */
  ptrdiff_t hscroll_max = min (MOST_POSITIVE_FIXNUM, PTRDIFF_MAX);
  ptrdiff_t new_hscroll = clip_to_bounds (0, hscroll, hscroll_max);
```

my current Rust draft of which is

```rust
    // Horizontal scrolling has problems with large scroll amounts.
    // It's too slow with long lines, and even with small lines the
    // display can be messed up.  For now, though, impose only the limits
    // required by the internal representation: horizontal scrolling must
    // fit in fixnum (since it's visible to Elisp) and into isize
    // (since it's stored in a ptrdiff_t).
    let hscroll_max = MOST_POSITIVE_FIXNUM as isize;
    let new_hscroll = clip_to_bounds(0, hscroll, hscroll_max);
```

And no, `EmacsInt::from(new_hscroll)` gives me this error:

```
1634 |     EmacsInt::from(new_hscroll)
     |     ^^^^^^^^^^^^^^ the trait `std::convert::From<isize>` is not implemented for `i64`
```

I assume this is because `isize` could in theory be an `i128`. The `try_from` approach above compiles fine and would panic in case of conversion failure - but perhaps that is overkill since it's probably not likely we'll see 128-bit processor architectures anytime soon, so maybe a silently lossy `new_hscroll as EmacsInt` is fine in this case. For correctness I'd say a panic is better, but I know nothing about how the two compare in terms of performance.

[snip]: https://github.com/remacs/remacs/blob/master/src/window.c#L527

**Comment by shaleh** [comment]
If you write it using `as EmacsInt` what does Clippy recommend if anything?

**Comment by shaleh** [comment]
`#define MOST_POSITIVE_FIXNUM (EMACS_INT_MAX >> INTTYPEBITS)`

`PTRDIFF_MAX` is defined as the largest value it can be based on the bit size. So to mimic the C you would write:
`let hscroll_max = min(MOST_POSITIVE_FIXNUM, isize::max_value());`

**Comment by emlun** [comment]
Ah, thanks for the `isize::max_value()` tip. I think this will end up as a match statement since `std::cmp::min` requires both arguments to be of the same type.

Hm, clippy doesn't say anything at all about `new_hscroll as EmacsInt` (where `new_hscroll: isize`). Does that mean it's fine to use?

**Comment by shaleh** [comment]
yep, fine then. We see complaints from clippy where it informs us the cast is unsafe/unstable and to prefer From<> instead.

**Comment by emlun** [comment]
Ok, cool. I also realized that `new_hscroll` necessarily has to fit in an `EmacsInt` in this case, because `0 <= new_hscroll <= hscroll` where `hscroll: EmacsInt`. :)

Expect a pull request shortly, once I've seen my tests succeed on C, fail on a Rust skeleton, then succeed again on fully ported Rust.
