### ISSUE TITLE
Port scan-sexps

### ISSUE THREAD

**Issue by brotzeit** [remacs/remacs#1430]
```c
DEFUN ("scan-sexps", Fscan_sexps, Sscan_sexps, 2, 2, 0,
       doc: /* Scan from character number FROM by COUNT balanced expressions.
If COUNT is negative, scan backwards.
Returns the character number of the position thus found.

Comments are ignored if `parse-sexp-ignore-comments' is non-nil.

If the beginning or end of (the accessible part of) the buffer is reached
in the middle of a parenthetical grouping, an error is signaled.
If the beginning or end is reached between groupings
but before count is used up, nil is returned.  */)
  (Lisp_Object from, Lisp_Object count)
{
  CHECK_NUMBER (from);
  CHECK_NUMBER (count);

  return scan_lists (XINT (from), XINT (count), 0, 1);
}
```

**Comment by seifriedc** [comment]
Hi, I'm new to the project but I've started to work on this. I think I have something that works, but I should see if I can add some tests as well.

**Comment by brotzeit** [comment]
Nice! If you have questions, just ask.

**Comment by seifriedc** [comment]
Thanks! I do have a question: how do we go about testing this? I'd imagine we have to use a temp-buffer, e.g.,
```
(ert-deftest test-scan-sexps ()
  (with-temp-buffer
    (- 1 2)
    (should (eq (scan-sexps 0 1) 8))))
```

But for some reason `scan-sexps` always returns nil. Any thoughts?

**Comment by shaleh** [comment]
http://ftp.gnu.org/old-gnu/Manuals/elisp-manual-20-2.5/html_node/elisp_566.html

> If it reaches the beginning or end between groupings but before count is used up, nil is returned.

the temp buffer is empty so it found nothing and returned nil.

`(- 1 2)` this computes -1 but does nothing with the value. If you look at cus-tests.el you see this:
```
	      (with-temp-buffer
		(insert-file-contents (locate-library "cus-load.el"))
```
which loads `cus-load.el` into the temp buffer.

from char-fold-tests.el
```
    (with-temp-buffer
      (save-excursion (insert string))
```
Puts the contents of `'string` into the buffer.

**Comment by seifriedc** [comment]
That makes sense, thanks for the help!

I have another question. In `syntax.rs` there is a `scan_lists_lisp` function, which just calls the C function `scan_lists`:
```rust
#[lisp_fn(name = "scan-lists", c_name = "scan_lists")]
pub fn scan_lists_lisp(from: EmacsInt, count: EmacsInt, depth: EmacsInt) -> LispObject {
    unsafe { scan_lists(from, count, depth, false) }
}
```
I'm confused as to why the `scan_lists_lisp` function exists. Is it that the implementation is temporary until someone ports `scan_lists`?

**Comment by shaleh** [comment]
Ah. Yes, I think this is in our docs. Let me explain it here and then would you please verify the docs exist?

`scan_lists` is a C function. It can be directly called. Where the confusion comes from is In the original C code, `DEFUN ("scan-lists",.......)` is also defined. This creates a function called `Fscan_lists` that can be called from C and exports into elisp as `(scan-lists ...)`. Whenever you call an elisp function it either calls another elisp function or becomes a function with a capital `F` in front like `Fscan_lists`. As you can see `Fscan_lists` and `scan_lists` are not the same and one can call the other.

When we port DEFUN to Rust we typically make the Rust function name the same as the name in the DEFUN, "scan_lists" in this case. On top of this the `lisp_fn` macro defines `Fscan_lists` for us which will end up looking like this:
```
pub fn Fscan_lists(from: LispObject, count: LispObject, depth: LispObject) -> LispObject {
    let result = scan_lists(from.into(), count.into(), depth.into());
    result.into()
}
```

But now you see the problem. If we name the Rust function `scan_lists` we cannot also name a C function `scan_lists`. C did not have this problem because it only had `Fscan_lists` and `scan_lists`. So to work around this we name the Rust function `scan_lists_lisp` (since it is the interface from lisp into Rust). Now in Rust code, either `scan_lists_lisp()` or `Fscan_lists` can be called as appropriate. In C, only `Fscan_lists` is called.

It is our preference to work with Rust functions with Rust types. The `F` functions exist for C and to expose functionality into elisp. Sometimes you will also see `rust_foo` instead of `foo`. This is where there is a Rust version and a C version but no elisp export.

**Comment by seifriedc** [comment]
Ah I think I'm beginning to understand. `Fscan_lists` refers to the `DEFUN("scan-lists" ...)` Lisp primitive implementation, meanwhile `scan_lists` is a (different) C function.
