### ISSUE TITLE
Make this project more viable: change the license

### ISSUE THREAD

**Issue by liquidaty** [remacs/remacs#1591]
Just an idea here to make your project more viable in the long run.

If you are rewriting emacs, why keep its restrictive license, which likely is the #1 reason emacs (unlike vim, for example) is not standard software bundled on every computer?

It is no wonder that interest in vim is holding steady over time and emacs interest over time is going down to zero. I love emacs and hate to see it die, but it will if the license doesn't change. 

Ask yourself how much the community has contributed to GPL3 code in the last decade vs how much it has contributed to more permissively licensed code (Apache, MIT etc). An d if you don't trust that gut reaction, there is plenty of research showing that copyleft is dying. Below (from whitesourcesoftware) summarizes what has been consistently observed by many parties:

![image](https://user-images.githubusercontent.com/26302468/102720158-adaecc00-42c0-11eb-8c59-98ecd04dc621.png)

Below are from Google trends as of today (Dec 2020). And if you check any other popular programming text editor (sublime, notepad++ etc), the numbers are all above emacs':

emacs:
![image](https://user-images.githubusercontent.com/26302468/102719998-6d9b1980-42bf-11eb-9abc-48443475cc23.png)

vim:
![image](https://user-images.githubusercontent.com/26302468/102720040-c7034880-42bf-11eb-91d8-82168a2c039d.png)

**Comment by db48x** [comment]
It's an idea, but there's just no way to just change the license without asking every individual Emacs contributor for permission. Most of them wouldn't give that permission, and all of them would be annoyed at anyone who asked.

**Comment by liquidaty** [comment]
If you use a clean-room approach, you can establish a reasonable legal position that the work is not derivative and therefore you don't have to ask for permission from the emacs team. But I understand that may not be practical, even if you do buy that reasoning.

**Comment by db48x** [comment]
That is technically possible, but this project is predicated on Rust's excellent FFI support so that we can write the code gradually, keeping it working the whole time. A clean-room implementation would need to start from scratch.

**Comment by nickdrozd** [comment]
This is a truly wretched idea. I hereby deny permission for any Remacs code I've written to be used for any attempts to undermine user freedoms, including switching to a "permissive" license.

**Comment by liquidaty** [comment]
I have no argument with @db48x 's response, I think it's entirely reasonable, and I respect that position that the problems of pursuing such an approach outweigh the benefits. That said, @nickdrozd, I can respect you calling the idea "wretched" if you can honestly say that you do not benefit from permissively licensed libraries, including the many that are baked into your desktop and device operating systems, the browser in which you likely posted your response, and other ubiquitous software that most people generally take for granted. My inquiry was based on an evidence-driven reality that the future success of this project could potentially be positively impacted by a permissive license and to devolve the conversation into such simplistic and idealistic terms only serves to undermine your credibility and more importantly, to do a disservice to the project to which you are contributing. Perhaps in the future if this project goes the way that other viral license projects have gone-- that is, been supplanted and surpassed by them-- then this idea in hindsight would not seem "wretched". But maybe that day will never come. Anyway, feel free to reply but I will not respond further.

**Comment by db48x** [comment]
@liquidaty, when I said that people would be "annoyed" at you for asking, this is what I meant. Many people in the Emacs and Remacs communities are strongly motivated by the ideology of Free software, and pragmatism about the absolute number of users doesn't enter in to their calculations very often.

**Comment by brotzeit** [comment]
To be honest, things like "ideology of Free software" result in people that see themselves as leaders of this movement(I think I don't have to mention names). I don't think it's really "free" when one person(or a bunch of people) dictates what is free and what not. The last term I'm thinking of is "free" when I look at the emacs mailing list. Many discussions rather look like "do it my way or fuck off".

I don't like to see the term ideology when talking about free software because it suggests that certain things are not even allowed to be mentioned. I would prefer an open-minded environment where anybody can say his opinion. Just because you put a sticker with "free software"(GPL3) on it doesn't make it "free".

I think we currently can observe something similar in our "modern democratic societies". Everybody is equal and free etc., but if you dare to question certain things you will be branded as XXX. Doesn't sound very free to me, but maybe I just don't get what free means.

**Comment by ZelphirKaltstahl** [comment]
Can we stop bashing the free software movement please? I cannot stand the whining any longer.

Some of the arguments raised here are ridiculous, to say the least, and very uninformed. Please spend a little more time on mailing lists and in the free software environment, before you write nonsense. It is really starting to annoy me, that you are trying to drag these communities down. They are some of the most supportive communities I ever had the privilege to enjoy and take part in.

"Ideology" in itself is not a bad word or a bad thing. It might have bad connotations, but in the end, you could probably describe any mindset as an ad-hoc ideology. Personally I do not necessarily feel it is a bad thing to have an ideology. It is similar to anyone being called an "idealist". Some people think that is a bad thing, but personally I think "Ah someone who puts an idea above other things to consider. Lets take a look at the idea!" and in case of the free software movement, I very much like that idea.

The OP was already a chain of wrong premises, but I restrained myself. Then we have people like brotzeit, who perhaps had one bad experience on a mailing list once and now spread rumors about it. I am personally often reading on Emacs mailing list and I cannot confirm what brotzeit said. Then brotzeit writes nonsense phrases like:

> Just because you put a sticker with "free software"(GPL3) on it doesn't make it "free".

Actually it does, because the license and some other licenses embody the values, which are demanded for free software. If you have a problem with a specific community, perhaps you can criticize that community instead. The fact stands, that you are free to fork Emacs and start releasing your own modifications. No one is holding you back. You cannot force other people to do as you want. For example you cannot force people to help you in a specific way, different from their own experience and way that they have suggested. No freedom respecting license will help you with that.

Lastly, how does a permissive license magically add users or developers?

Actually, since many people in the Emacs community enjoy the free software environment, you would immediately lose contributors. Many users of computer software do not have a lot of knowledge about licenses and what their effects are on the user, so as long as they can download it and install it, those users will not care, whether it is GPL or a different license. The users, who do care however, have no reason not to use a GPL licensed software, comparing to the same software under lets say MIT license (also known as I don't give a f* license). It does not take away any of their rights. It makes sure, that they keep their rights instead, using the copyleft concept.

If someone personally has a problem with contributing to a GPL licensed project, then perhaps the problem is not the one of the project being licensed GPL, but a personal issue. I for one have not seen a more freedom respecting and helpful community, than the free software project communities, that I am participating in, so please stop.

**Comment by brotzeit** [comment]
My post was probably strongly influenced by my current, general frustration which is not related to emacs or free software in general. I apologize for this.
